name: "Integrate"

on:
  pull_request: null
  push: null

jobs:
  tests:
    name: "Tests"

    runs-on: "${{ matrix.operating-system }}"

    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
          - "macos-latest"

        php-version:
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies with composer"
        run: "composer -n install"

      - name: "Run tests with phpunit/phpunit"
        run: "bin/phpunit"
